version: "3.6"
services:
  
  groupoffice:
    build:
      context: ./groupoffice
    restart: always
    ports:
      - "8000:80"
        # - "443:443"
    links:
      - db

    volumes:
      - ./src/master:/usr/local/share/src:delegated 
      - "godata:/var/lib/groupoffice"
      #- "./profile:/tmp/profile:delegated"
      - "goetc:/etc/groupoffice/multi_instance"
      - ./groupoffice/etc/groupoffice/globalconfig.inc.php:/etc/groupoffice/globalconfig.inc.php:delegated

      #- ./ssl:/etc/ssl/groupoffice:delegated
    env_file:
      - ./db.env     
    environment:
      # for profiling set and enable the bind mount above:
#      XDEBUG_MODE: "profile"

      MYSQL_DATABASE: groupoffice
      PHP_IDE_CONFIG: "serverName=localhost" #for PHPStorm path mappings in Preferences -> PHP -> Servers

    working_dir: /usr/local/share/src

  db:
    image: mariadb
    restart: always   
    ports:
      - "8306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: groupoffice
    env_file:
      - ./db.env     

    volumes:
      - "dbdata:/var/lib/mysql"
      - ~/Downloads:/root/Downloads:delegated # Useful for importing large dump files
      
  mailserver:
    image: intermesh/groupoffice-mailserver
    ## When using local builds for testing:
    #build:
    #   context: ../docker-groupoffice-mailserver
    restart: always
    ports: 
      - "143:143"
      - "4190:4190"
      - "25:25"
      - "587:587"
    env_file:
      - ./db.env
    environment:
      POSTMASTER_EMAIL: admin@intermesh.localhost
    volumes:
      - "vmail:/var/mail/vhosts"
      - ~/Downloads:/root/Downloads:delegated # Useful for importing email source files

  sass:
    restart: always
    build:
       context: ./sass    
    volumes: 
      - ./src:/src
    working_dir: /src

volumes:
  godata:
  goetc:
  dbdata:
  vmail:
