version: "3.1"
services:
  groupoffice:
    image: intermesh/groupoffice
    container_name: groupoffice
    restart: always
    build:
      context: ./groupoffice
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./src/groupoffice/www:/usr/local/share/groupoffice:cached
      - ./data/files:/srv/groupoffice:cached
    env_file:
      - ./db.env
  db:
    container_name: db
    image: mariadb
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
    env_file:
      - ./db.env
    ports:
      - "8306:3306"
      
  mailserver:
    image: intermesh/mailserver
    container_name: mailserver
    restart: always
    build:
      context: ./mailserver
    ports: 
      - "143:143"
      - "4190:4190"
      - "25:25"
      - "587:587"
    env_file:
      - ./db.env
    environment:
      POSTMASTER_EMAIL: postmaster@example.com
    volumes:
      - ./data/vmail:/var/mail/vhosts:cached
      
  composer:
    container_name: composer
    build:
       context: ./composer
    volumes: 
      - ./src/groupoffice/www:/var/www/html
    working_dir: /var/www/html
    
  sass:
    container_name: sass
    build:
       context: ./sass       
    volumes: 
      - ./src/groupoffice/www:/var/www/html
    working_dir: /var/www/html
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links: 
     - db:db
    env_file:
      - ./db.env
    restart: always
    ports:
     - 8001:80
    volumes:
     - /sessions  
