#!/bin/bash
set -e

if [ -z "$1" ] 
then
	BRANCH=""
else
	BRANCH="-$1"
fi

if [ -z "$2" ]
then 
	P="tests"
else
	P=$2
fi

echo "Running test in container groupoffice$BRANCH"


#docker-compose exec -u www-data -e XDEBUG_SESSION=1 groupoffice$BRANCH ./www/vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml $P
docker-compose exec -u www-data groupoffice$BRANCH ./www/vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml $P
